mysql -u root -ppassword -D tpch < ./1.sql
mysql -u root -ppassword -D tpch < ./2.sql
mysql -u root -ppassword -D tpch < ./3.sql
mysql -u root -ppassword -D tpch < ./4.sql
mysql -u root -ppassword -D tpch < ./5.sql
mysql -u root -ppassword -D tpch < ./6.sql
mysql -u root -ppassword -D tpch < ./7.sql
mysql -u root -ppassword -D tpch < ./8.sql
mysql -u root -ppassword -D tpch < ./9.sql
mysql -u root -ppassword -D tpch < ./10.sql
mysql -u root -ppassword -D tpch < ./11.sql
mysql -u root -ppassword -D tpch < ./12.sql
mysql -u root -ppassword -D tpch < ./13.sql
mysql -u root -ppassword -D tpch < ./14.sql
mysql -u root -ppassword -D tpch < ./15.sql
mysql -u root -ppassword -D tpch < ./16.sql
mysql -u root -ppassword -D tpch < ./17.sql
mysql -u root -ppassword -D tpch < ./18.sql
mysql -u root -ppassword -D tpch < ./19.sql
mysql -u root -ppassword -D tpch < ./20.sql
mysql -u root -ppassword -D tpch < ./21.sql
mysql -u root -ppassword -D tpch < ./22.sql
